# Universidad Libre - Seccional Cali<br>Facultad de Ingeniería - Diplomado en Ciencia de Datos<br>(ↄ) Juan Sebastian Diaz Campos, 2026

# 02_limpieza
Plantilla para el desarrollo del proyecto del diplomado de Ciencia de Datos, aplicando buenas prácticas.

---

Este cuaderno se dedica a la crucial tarea de preparar los datos para el análisis, asegurando su calidad y consistencia. La limpieza de datos es fundamental para obtener resultados confiables en las etapas posteriores.

**Propósito:** Mejorar la calidad de los datos mediante la corrección de errores, estandarización de formatos y aplicación de reglas de calidad.

**Tareas habituales:**
- Detección y tratamiento de valores nulos (Completar datos faltantes)
- Estandarización de formatos (nombres, fechas, números, texto)
- Identificación y corrección de outliers
- Corrección de errores tipográficos
- Normalizar/Homogeneizar datos
- Validación de reglas de negocio
- Documentación de transformaciones aplicadas
- Verificación de consistencia en los datos
- Eliminar columnas o filas
- Crear columnas nuevas

In [69]:
import os
import pandas as pd

In [70]:
cwd = os.getcwd() # current working directory
landing_dir = cwd + '/../data/landing/'
trusted_dir = cwd + '/../data/trusted/'

In [71]:
df = pd.read_csv(landing_dir + 'historico_solicitudes.csv')

In [72]:
df

,Número,Fecha de entrega,Fecha de cierre,Prioridad,Estado,Título,Cerrado por,Nombre de Aplicación,Categoría del sitio,Bdo Tipo de Solicitud,Tipo solici,Tipo de Solicitud
0,RF699325,29/04/25 10:24:20,02/05/25 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
1,RF699520,29/04/25 12:33:42,02/05/25 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,A,NaN,NaN,NaN
2,RF699819,29/04/25 16:53:16,06/05/25 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
3,RF700695,02/05/25 08:56:25,05/05/25 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
4,RF700696,02/05/25 08:56:28,02/05/25 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,26/05/26 09:32:41,26/05/26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5883,RF878267,09/06/26 18:08:52,17/06/26 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN
5884,RF878819,10/06/26 16:01:26,07/07/26 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5885,RF878901,10/06/26 17:30:24,17/06/26 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT IZQUIERDO,A,NaN,NaN,NaN
5886,RF879212,11/06/26 11:49:58,17/06/26 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN

## 1. Modificar nombres de las columnas para mayor entendimiento

In [73]:
df.columns = ['ID_caso', 'Fecha_apertura', 'Fecha_cierre', 'Prioridad', 'Estado','Titulo_caso', 'Responsable_atencion','Aplicacion','Sitio','Tipo_solicitud_1', 'Tipo_solicitud_2', 'Tipo_solicitud_3']

In [74]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
0,RF699325,29/04/25 10:24:20,02/05/25 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
1,RF699520,29/04/25 12:33:42,02/05/25 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,A,NaN,NaN,NaN
2,RF699819,29/04/25 16:53:16,06/05/25 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
3,RF700695,02/05/25 08:56:25,05/05/25 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
4,RF700696,02/05/25 08:56:28,02/05/25 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,26/05/26 09:32:41,26/05/26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5883,RF878267,09/06/26 18:08:52,17/06/26 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN
5884,RF878819,10/06/26 16:01:26,07/07/26 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5885,RF878901,10/06/26 17:30:24,17/06/26 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT IZQUIERDO,A,NaN,NaN,NaN
5886,RF879212,11/06/26 11:49:58,17/06/26 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN

## 2. Analizar el Dataset Actual

In [132]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5887 entries, 0 to 5886
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_caso               5887 non-null   str
 1   Fecha_apertura        5887 non-null   datetime64[us]
 2   Fecha_cierre          5887 non-null   datetime64[us]
 3   Prioridad             5887 non-null   str
 4   Estado                5887 non-null   str
 5   Titulo_caso           5887 non-null   str
 6   Responsable_atencion  5887 non-null   str
 7   Aplicacion            5887 non-null   str
 8   Sitio                 5887 non-null   str
 9   Tipo_solicitud_1      5887 non-null   str
 10  Tipo_solicitud_2      0 non-null      float64
 11  Tipo_solicitud_3      0 non-null      float64
dtypes: datetime64[us](2), float64(2), str(8)
memory usage: 552.0 KB

In [133]:
df.isnull().sum()

ID_caso                    0
Fecha_apertura             0
Fecha_cierre               0
Prioridad                  0
Estado                     0
Titulo_caso                0
Responsable_atencion       0
Aplicacion                 0
Sitio                      0
Tipo_solicitud_1           0
Tipo_solicitud_2        5887
Tipo_solicitud_3        5887
dtype: int64

In [151]:
print(df.duplicated().sum())

0

In [134]:
df.describe(include="all")

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
count,5887,5887,5887,5887,5887,5887,5887,5887,5887,5887,0.0,0.0
unique,5887,NaN,NaN,1,1,3054,7,17,1,6,NaN,NaN
top,RF699325,NaN,NaN,4 - Baja,Cerrado,DESBLOQUEO DE USUARIO,JZAMORANO,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
freq,1,NaN,NaN,5887,5887,123,2291,3321,5887,4031,NaN,NaN
mean,NaN,2025-05-31 01:14:13.350093,2025-06-04 19:32:54.736028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,2024-05-06 14:12:53,2024-05-08 16:27:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2024-12-20 02:05:16,2024-12-26 11:27:54.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,2025-05-07 07:34:05,2025-05-09 16:54:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2025-12-03 12:28:41,2025-12-09 10:10:51.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,2026-06-30 15:48:23,2026-07-07 19:47:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [174]:
for col in ["Sitio", "Estado", "Tipo_solicitud_1", "Prioridad", "Aplicacion"]:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

Sitio
Sitio
EDIFICIO PRINCIPAL    5887
Name: count, dtype: int64

Estado
Estado
Cerrado    5887
Name: count, dtype: int64

Tipo_solicitud_1
Tipo_solicitud_1
DESBLOQUEO        4048
CREACION           960
OTRA SOLICITUD     753
MODIFICACION       111
ELIMINACION         15
Name: count, dtype: int64

Prioridad
Prioridad
4 - Baja    5887
Name: count, dtype: int64

Aplicacion
Aplicacion
FIRST VISION                                     3321
IRON MOUNTAIN (Documenta Web)                    1555
SERIVA                                            386
SWIFT                                             209
KONCILIA                                          132
ALFYN                                              82
DECEVAL                                            66
BANKTRADE                                          51
CLEARSTREAM                                        30
CRCC                                               26
MAILPOINT                                          16
MEC BACK OFFICE                                     5
UNIFIRMAS                                           3
OTRA APP                                            2
liquidaciones de crédito de moneda extranjera       1
MONEXT                                              1
SISCAR                                              1
Name: count, dtype: int64

## 3. Preparar columnas del Dataset según la información que representan

In [78]:
df["Fecha_cierre"] = pd.to_datetime(
    df["Fecha_cierre"],
    format="%d/%m/%y %H:%M:%S"
)

In [79]:
df["Fecha_apertura"] = pd.to_datetime(
    df["Fecha_apertura"],
    format="%d/%m/%y %H:%M:%S"
)

In [124]:
df["Aplicacion"] = df["Aplicacion"].replace({
    "FIRST DATA": "FIRST VISION",
    "SWIFT IZQUIERDO": "SWIFT",
    "SWIFT DERECHO": "SWIFT",
    "SERIVA RENTA FIJA": "SERIVA"
})

df["Aplicacion"] = df["Aplicacion"].fillna("OTRA APP")

In [125]:
def cambiar_sitio(valor):
    if valor == "A":
        return "EDIFICIO PRINCIPAL"
    elif valor == "B":
        return "OFICINA BANCO"
    elif valor == "C":
        return "OFICINA BANCO"
    elif valor == "D":
        return "AREA ESPECIAL"
    else:
        return "EDIFICIO PRINCIPAL"

df["Sitio"] = df["Sitio"].apply(cambiar_sitio)

In [143]:
diccionario_solicitudes = {
    "CREACIÓN": "CREACION",
    "CREACION": "CREACION",
    "CREAR": "CREACION",
    "ASIGNACION": "CREACION",
    "ASIGNACIÓN": "CREACION",
    "MODIFICACION": "MODIFICACION",
    "MODIFICACIÓN": "MODIFICACION",
    "CAMBIAR": "MODIFICACION",
    "ELIMINACIÓN": "ELIMINACION",
    "ELIMINAR": "ELIMINACION",
    "DESBLOQUEO": "DESBLOQUEO",
    "DESBLOQUEAR": "DESBLOQUEO",
    "ACTIVACION": "DESBLOQUEO",
    "ACTIVAR": "DESBLOQUEO",
    "RESETEO": "DESBLOQUEO",
    "CONTRASEÑA": "DESBLOQUEO",
    "PASSWORD": "DESBLOQUEO",
    "CLAVE": "DESBLOQUEO",
    "REACTIVACION": "DESBLOQUEO",
    "RECUPERACION": "DESBLOQUEO",
    "RECUPERACIÓN": "DESBLOQUEO",
    "RESET": "DESBLOQUEO"
}

for palabra, tipo in diccionario_solicitudes.items():
    mask = df["Titulo_caso"].str.contains(palabra, case=False, na=False)
    df.loc[mask, "Tipo_solicitud_1"] = tipo

df["Tipo_solicitud_1"] = df["Tipo_solicitud_1"].fillna("OTRA SOLICITUD")

In [145]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION,NaN,NaN
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION,NaN,NaN
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN

## 4. Preparar el Dataset quitando columnas o filas vacías y/o con valores que no corresponden

In [177]:
# Cantidad de registros antes
print(f"Registros totales antes: {len(df)}")

# Eliminar aplicaciones que no corresponden
df = df[~df["Aplicacion"].isin(["liquidaciones de crédito de moneda extranjera", "SISCAR", "MONEXT"])]

# Cantidad de registros después
print(f"Registros totales después: {len(df)}")

Registros totales antes: 5887
Registros totales después: 5884

In [178]:
df = df.dropna(axis=1, how="all")

In [179]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO

## 5. Crear columnas nuevas según el Dataset actual

In [123]:
# crear columnas nuevas
df['dia'] = df.fecha.dt.day
df['mes'] = df.fecha.dt.month
df['año'] = df.fecha.dt.year
df['weekday'] = df.fecha.dt.weekday

AttributeError: 'DataFrame' object has no attribute 'fecha'

In [29]:
df

         fecha   SKU   vental_total  dia  mes   año  weekday
0   2022-11-01  1434  121672.710000    1   11  2022        1
1   2022-11-02  1656  133636.640000    2   11  2022        2
2   2022-11-03  1875  210932.180000    3   11  2022        3
3   2022-11-04  1434  111660.390000    4   11  2022        4
4   2022-11-05  1545  146417.560000    5   11  2022        5
..         ...   ...            ...  ...  ...   ...      ...
512 2024-03-27  1156  452331.135622   27    3  2024        2
513 2024-03-28  1375  246045.083440   28    3  2024        3
514 2024-03-29   934  425815.429745   29    3  2024        4
515 2024-03-30  1156  320997.018300   30    3  2024        5
516 2024-03-31  1375  435508.682266   31    3  2024        6

[517 rows x 7 columns]

In [31]:
wd = ['L', 'M', 'X', 'J', 'V', 'S', 'D']
df['dia_semana'] = df.fecha.dt.weekday.apply(lambda x: wd[x])

In [33]:
df

         fecha   SKU   vental_total  dia  mes   año  weekday dia_semana
0   2022-11-01  1434  121672.710000    1   11  2022        1          M
1   2022-11-02  1656  133636.640000    2   11  2022        2          X
2   2022-11-03  1875  210932.180000    3   11  2022        3          J
3   2022-11-04  1434  111660.390000    4   11  2022        4          V
4   2022-11-05  1545  146417.560000    5   11  2022        5          S
..         ...   ...            ...  ...  ...   ...      ...        ...
512 2024-03-27  1156  452331.135622   27    3  2024        2          X
513 2024-03-28  1375  246045.083440   28    3  2024        3          J
514 2024-03-29   934  425815.429745   29    3  2024        4          V
515 2024-03-30  1156  320997.018300   30    3  2024        5          S
516 2024-03-31  1375  435508.682266   31    3  2024        6          D

[517 rows x 8 columns]

**Último paso**: Guardar los datos limpios, con calidad, estandarizados, etc.

In [35]:
df.to_csv(trusted_dir + 'datos_limpios.csv', index=False)