# Universidad Libre - Seccional Cali<br>Facultad de Ingeniería - Diplomado en Ciencia de Datos<br>(ↄ) Juan Sebastian Diaz Campos, 2026

# 02_limpieza
Plantilla para el desarrollo del proyecto del diplomado de Ciencia de Datos, aplicando buenas prácticas.

---

Este cuaderno se dedica a la crucial tarea de preparar los datos para el análisis, asegurando su calidad y consistencia. La limpieza de datos es fundamental para obtener resultados confiables en las etapas posteriores.

**Propósito:** Mejorar la calidad de los datos mediante la corrección de errores, estandarización de formatos y aplicación de reglas de calidad.

**Tareas habituales:**
- Detección y tratamiento de valores nulos (Completar datos faltantes)
- Estandarización de formatos (nombres, fechas, números, texto)
- Identificación y corrección de outliers
- Corrección de errores tipográficos
- Normalizar/Homogeneizar datos
- Validación de reglas de negocio
- Documentación de transformaciones aplicadas
- Verificación de consistencia en los datos
- Eliminar columnas o filas
- Crear columnas nuevas

In [1]:
import os
import pandas as pd
import holidays
import numpy as np

In [2]:
cwd = os.getcwd() # current working directory
landing_dir = cwd + '/../data/landing/'
trusted_dir = cwd + '/../data/trusted/'

In [3]:
df = pd.read_csv(landing_dir + 'historico_solicitudes.csv')

In [4]:
df

,Número,Fecha de entrega,Fecha de cierre,Prioridad,Estado,Título,Cerrado por,Nombre de Aplicación,Categoría del sitio,Bdo Tipo de Solicitud,Tipo solici,Tipo de Solicitud
0,RF699325,29/04/25 10:24:20,02/05/25 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
1,RF699520,29/04/25 12:33:42,02/05/25 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,A,NaN,NaN,NaN
2,RF699819,29/04/25 16:53:16,06/05/25 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
3,RF700695,02/05/25 08:56:25,05/05/25 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
4,RF700696,02/05/25 08:56:28,02/05/25 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,26/05/26 09:32:41,26/05/26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5883,RF878267,09/06/26 18:08:52,17/06/26 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN
5884,RF878819,10/06/26 16:01:26,07/07/26 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5885,RF878901,10/06/26 17:30:24,17/06/26 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT IZQUIERDO,A,NaN,NaN,NaN
5886,RF879212,11/06/26 11:49:58,17/06/26 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN

## 1. Modificar nombres de las columnas para mayor entendimiento

In [5]:
df.columns = ['ID_caso', 'Fecha_apertura', 'Fecha_cierre', 'Prioridad', 'Estado','Titulo_caso', 'Responsable_atencion','Aplicacion','Sitio','Tipo_solicitud_1', 'Tipo_solicitud_2', 'Tipo_solicitud_3']

In [6]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
0,RF699325,29/04/25 10:24:20,02/05/25 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
1,RF699520,29/04/25 12:33:42,02/05/25 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,A,NaN,NaN,NaN
2,RF699819,29/04/25 16:53:16,06/05/25 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
3,RF700695,02/05/25 08:56:25,05/05/25 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,A,NaN,NaN,NaN
4,RF700696,02/05/25 08:56:28,02/05/25 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST DATA,A,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,26/05/26 09:32:41,26/05/26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5883,RF878267,09/06/26 18:08:52,17/06/26 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN
5884,RF878819,10/06/26 16:01:26,07/07/26 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT DERECHO,A,NaN,NaN,NaN
5885,RF878901,10/06/26 17:30:24,17/06/26 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT IZQUIERDO,A,NaN,NaN,NaN
5886,RF879212,11/06/26 11:49:58,17/06/26 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT DERECHO,A,NaN,NaN,NaN

## 2. Analizar el Dataset Actual

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5887 entries, 0 to 5886
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_caso               5887 non-null   str
 1   Fecha_apertura        5887 non-null   str
 2   Fecha_cierre          5887 non-null   str
 3   Prioridad             5887 non-null   str
 4   Estado                5887 non-null   str
 5   Titulo_caso           5887 non-null   str
 6   Responsable_atencion  5887 non-null   str
 7   Aplicacion            5885 non-null   str
 8   Sitio                 5887 non-null   str
 9   Tipo_solicitud_1      2 non-null      str
 10  Tipo_solicitud_2      0 non-null      float64
 11  Tipo_solicitud_3      0 non-null      float64
dtypes: float64(2), str(10)
memory usage: 552.0 KB

In [8]:
df.isnull().sum()

ID_caso                    0
Fecha_apertura             0
Fecha_cierre               0
Prioridad                  0
Estado                     0
Titulo_caso                0
Responsable_atencion       0
Aplicacion                 2
Sitio                      0
Tipo_solicitud_1        5885
Tipo_solicitud_2        5887
Tipo_solicitud_3        5887
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [10]:
df.describe(include="all")

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
count,5887,5887,5887,5887,5887,5887,5887,5885,5887,2,0.0,0.0
unique,5887,5887,5887,1,1,3054,7,19,4,1,NaN,NaN
top,RF699325,29/04/25 10:24:20,02/05/25 11:58:20,4 - Baja,Cerrado,DESBLOQUEO DE USUARIO,JZAMORANO,FIRST DATA,A,Creacion,NaN,NaN
freq,1,1,1,5887,5887,123,2291,2647,3153,2,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for col in ["Sitio", "Estado", "Tipo_solicitud_1", "Prioridad", "Aplicacion"]:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

Sitio
Sitio
A    3153
B    2365
C     216
D     153
Name: count, dtype: int64

Estado
Estado
Cerrado    5887
Name: count, dtype: int64

Tipo_solicitud_1
Tipo_solicitud_1
NaN         5885
Creacion       2
Name: count, dtype: int64

Prioridad
Prioridad
4 - Baja    5887
Name: count, dtype: int64

Aplicacion
Aplicacion
FIRST DATA                                       2647
IRON MOUNTAIN (Documenta Web)                    1555
FIRST VISION                                      674
SERIVA                                            331
KONCILIA                                          132
SWIFT IZQUIERDO                                   109
SWIFT DERECHO                                     100
ALFYN                                              82
DECEVAL                                            66
SERIVA RENTA FIJA                                  55
BANKTRADE                                          51
CLEARSTREAM                                        30
CRCC                                               26
MAILPOINT                                          16
MEC BACK OFFICE                                     5
UNIFIRMAS                                           3
NaN                                                 2
liquidaciones de crédito de moneda extranjera       1
MONEXT                                              1
SISCAR                                              1
Name: count, dtype: int64

## 3. Preparar columnas del Dataset según la información que representan

In [12]:
df["Fecha_cierre"] = pd.to_datetime(
    df["Fecha_cierre"],
    format="%d/%m/%y %H:%M:%S"
)

In [13]:
df["Fecha_apertura"] = pd.to_datetime(
    df["Fecha_apertura"],
    format="%d/%m/%y %H:%M:%S"
)

In [14]:
df["Aplicacion"] = df["Aplicacion"].replace({
    "FIRST DATA": "FIRST VISION",
    "SWIFT IZQUIERDO": "SWIFT",
    "SWIFT DERECHO": "SWIFT",
    "SERIVA RENTA FIJA": "SERIVA"
})

df["Aplicacion"] = df["Aplicacion"].fillna("OTRA APP")

In [15]:
def cambiar_sitio(valor):
    if valor == "A":
        return "EDIFICIO PRINCIPAL"
    elif valor == "B":
        return "OFICINA BANCO"
    elif valor == "C":
        return "OFICINA BANCO"
    elif valor == "D":
        return "AREA ESPECIAL"
    else:
        return "EDIFICIO PRINCIPAL"

df["Sitio"] = df["Sitio"].apply(cambiar_sitio)

In [16]:
diccionario_solicitudes = {
    "CREACIÓN": "CREACION",
    "CREACION": "CREACION",
    "CREAR": "CREACION",
    "ASIGNACION": "CREACION",
    "ASIGNACIÓN": "CREACION",
    "MODIFICACION": "MODIFICACION",
    "MODIFICACIÓN": "MODIFICACION",
    "CAMBIAR": "MODIFICACION",
    "ELIMINACIÓN": "ELIMINACION",
    "ELIMINAR": "ELIMINACION",
    "DESBLOQUEO": "DESBLOQUEO",
    "DESBLOQUEAR": "DESBLOQUEO",
    "ACTIVACION": "DESBLOQUEO",
    "ACTIVAR": "DESBLOQUEO",
    "RESETEO": "DESBLOQUEO",
    "CONTRASEÑA": "DESBLOQUEO",
    "PASSWORD": "DESBLOQUEO",
    "CLAVE": "DESBLOQUEO",
    "REACTIVACION": "DESBLOQUEO",
    "RECUPERACION": "DESBLOQUEO",
    "RECUPERACIÓN": "DESBLOQUEO",
    "RESET": "DESBLOQUEO"
}

for palabra, tipo in diccionario_solicitudes.items():
    mask = df["Titulo_caso"].str.contains(palabra, case=False, na=False)
    df.loc[mask, "Tipo_solicitud_1"] = tipo

df["Tipo_solicitud_1"] = df["Tipo_solicitud_1"].fillna("OTRA SOLICITUD")

In [17]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_solicitud_2,Tipo_solicitud_3
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION,NaN,NaN
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION,NaN,NaN
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,NaN,NaN

## 4. Preparar el Dataset quitando columnas o filas vacías y/o con valores que no corresponden

In [18]:
# Cantidad de registros antes
print(f"Registros totales antes: {len(df)}")

# Eliminar aplicaciones que no corresponden
df = df[~df["Aplicacion"].isin(["liquidaciones de crédito de moneda extranjera", "SISCAR", "MONEXT"])]

# Cantidad de registros después
print(f"Registros totales después: {len(df)}")

Registros totales antes: 5887
Registros totales después: 5884

In [19]:
df = df.dropna(axis=1, how="all")

In [20]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO
...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO

## 5. Crear columnas nuevas según el Dataset actual

In [21]:
festivos_colombia = holidays.Colombia(years=[2024, 2025, 2026])
def tipo_dia_calendario(fecha):
    fecha = fecha.date()
    if fecha.weekday() >= 5:      # 5 = sábado, 6 = domingo
        return "FESTIVO"
    if fecha in festivos_colombia: # día festivo en Colombia
        return "FESTIVO"
    return "HABIL"

df["Tipo_dia_apertura"] = df["Fecha_apertura"].apply(tipo_dia_calendario)
df["Tipo_dia_cierre"] = df["Fecha_cierre"].apply(tipo_dia_calendario)

In [24]:
df["Nro_dia_apertura"] = df["Fecha_apertura"].dt.day
df["Nro_dia_cierre"] = df["Fecha_cierre"].dt.day
df["Mes_apertura"] = df["Fecha_apertura"].dt.month
df["Mes_cierre"] = df["Fecha_cierre"].dt.month
df["Hora_apertura"] = df["Fecha_apertura"].dt.hour
df["Hora_cierre"] = df["Fecha_cierre"].dt.hour

df["Año_caso"] = np.where(
    df["Fecha_apertura"].dt.year == df["Fecha_cierre"].dt.year,
    df["Fecha_apertura"].dt.year,
    df["Fecha_cierre"].dt.year
)

In [25]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_dia_apertura,Tipo_dia_cierre,Nro_dia_apertura,Nro_dia_cierre,Mes_apertura,Mes_cierre,Hora_apertura,Hora_cierre,Año_caso
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,29,2,4,5,10,11,2025
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,29,2,4,5,12,9,2025
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION,HABIL,HABIL,29,6,4,5,16,14,2025
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,2,5,5,5,8,8,2025
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,2,2,5,5,8,11,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,26,26,5,5,9,16,2026
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,9,17,6,6,18,11,2026
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION,HABIL,HABIL,10,7,6,7,16,12,2026
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,10,17,6,6,17,11,2026
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,11,17,6,6,11,11,2026

In [26]:
festivos = np.array(list(festivos_colombia.keys()), dtype='datetime64[D]')

df["ANS_dias_laborales"] = df.apply(
    lambda x: np.busday_count(
        x["Fecha_apertura"].date(),
        x["Fecha_cierre"].date(),
        holidays=festivos
    ),
    axis=1
)

In [27]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,Tipo_dia_apertura,Tipo_dia_cierre,Nro_dia_apertura,Nro_dia_cierre,Mes_apertura,Mes_cierre,Hora_apertura,Hora_cierre,Año_caso,ANS_dias_laborales
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,29,2,4,5,10,11,2025,2
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,29,2,4,5,12,9,2025,2
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION,HABIL,HABIL,29,6,4,5,16,14,2025,4
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,2,5,5,5,8,8,2025,1
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,2,2,5,5,8,11,2025,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,26,26,5,5,9,16,2026,0
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,9,17,6,6,18,11,2026,5
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION,HABIL,HABIL,10,7,6,7,16,12,2026,17
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,10,17,6,6,17,11,2026,4
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,HABIL,HABIL,11,17,6,6,11,11,2026,3

In [28]:
def horario_laboral(fecha):
    if fecha.weekday() >= 5:
        return "SI"
    if fecha.hour >= 8 and fecha.hour < 18:
        return "NO"
    return "SI"

df["Apertura_fuera_horario"] = df["Fecha_apertura"].apply(horario_laboral)
df["Cierre_fuera_horario"] = df["Fecha_cierre"].apply(horario_laboral)
df["Cumple_ANS"] = df["ANS_dias_laborales"].apply(lambda x: "SI" if x <= 3 else "NO")

In [29]:
df

,ID_caso,Fecha_apertura,Fecha_cierre,Prioridad,Estado,Titulo_caso,Responsable_atencion,Aplicacion,Sitio,Tipo_solicitud_1,...,Nro_dia_cierre,Mes_apertura,Mes_cierre,Hora_apertura,Hora_cierre,Año_caso,ANS_dias_laborales,Apertura_fuera_horario,Cierre_fuera_horario,Cumple_ANS
0,RF699325,2025-04-29 10:24:20,2025-05-02 11:58:20,4 - Baja,Cerrado,Desbloqueo de aplicativo,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,...,2,4,5,10,11,2025,2,NO,NO,SI
1,RF699520,2025-04-29 12:33:42,2025-05-02 09:18:45,4 - Baja,Cerrado,ASIGNACION DE CLAVE MAILPOINT,JSDIAZ,MAILPOINT,EDIFICIO PRINCIPAL,DESBLOQUEO,...,2,4,5,12,9,2025,2,NO,NO,SI
2,RF699819,2025-04-29 16:53:16,2025-05-06 14:49:45,4 - Baja,Cerrado,Solicitud de creación de usuario FirstData - F...,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,CREACION,...,6,4,5,16,14,2025,4,NO,NO,NO
3,RF700695,2025-05-02 08:56:25,2025-05-05 08:40:49,4 - Baja,Cerrado,DESBLOQUEO ACCESO,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,...,5,5,5,8,8,2025,1,NO,NO,SI
4,RF700696,2025-05-02 08:56:28,2025-05-02 11:54:47,4 - Baja,Cerrado,DESBLOQUEO APLICATIVO FD - UGR,JSDIAZ,FIRST VISION,EDIFICIO PRINCIPAL,DESBLOQUEO,...,2,5,5,8,11,2025,0,NO,NO,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5882,RF872307,2026-05-26 09:32:41,2026-05-26 16:21:16,4 - Baja,Cerrado,DESBLOQUEAR USUARIO DE SWIFT 00951,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,...,26,5,5,9,16,2026,0,NO,NO,SI
5883,RF878267,2026-06-09 18:08:52,2026-06-17 11:35:34,4 - Baja,Cerrado,DOCIT - DESBLOQUEAR USUARIO SWIFT,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,...,17,6,6,18,11,2026,5,SI,NO,NO
5884,RF878819,2026-06-10 16:01:26,2026-07-07 12:35:17,4 - Baja,Cerrado,Modificacion de perfil,MRODRIGUEZPE,SWIFT,EDIFICIO PRINCIPAL,MODIFICACION,...,7,6,7,16,12,2026,17,NO,NO,NO
5885,RF878901,2026-06-10 17:30:24,2026-06-17 11:39:04,4 - Baja,Cerrado,Reset del Token Usuario de Swift : OCCICCD4,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,...,17,6,6,17,11,2026,4,NO,NO,NO
5886,RF879212,2026-06-11 11:49:58,2026-06-17 11:43:55,4 - Baja,Cerrado,DESBLOQUEAR SWIFT DERECHO,IAVILA,SWIFT,EDIFICIO PRINCIPAL,DESBLOQUEO,...,17,6,6,11,11,2026,3,NO,NO,SI

**Último paso**: Guardar los datos limpios, con calidad, estandarizados, etc.

In [30]:
df.to_csv(trusted_dir + 'datos_limpios.csv', index=False)